VMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),
    
    path('admin/', admin.site.urls),
    path('', include('visit.urls')),
    
]

visit/urls.py
from django.conf.urls import url
from django.urls import path
from django.urls.conf import include
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'visit'

urlpatterns = [
    path('', views.home, name='home'),
    path('newvisitor', views.newvisitor, name='newvisitor'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('visitor/', views.visitors, name='visitor'),


    path('Applicantsearch/',views.Applicantsearch,name='Applicantsearch'),
    path('visitorsearch/',views.searchVisitor,name='searchvisitor'),
    path('reject/<int:id>', views.RejectVisitorRequest, name="rejection"),
    path('changepass/', views.ChangePasswordView, name="changepass"),
    path('EditVisitortime/<int:id>',views.EditVisitorTime, name="Accept"),
    path('applicantSignup/', views.ApplicantSignUp, name='applicantSignup'),
    path('RemaningTimeToMeet/<int:pk>', views.RemaningTimeToMeet, name='RemaningTimeToMeet'),
    path('security_page/',views.security_page,name='security_page'),
    path('EntryTime/',views.EntryTime,name='EntryTime'),
    path('AcceptApplicents/<int:id>',views.AcceptApplicents,name='AcceptApplicents'),
    path('NewApplicants/',views.NewApplicants,name='NewApplicants'),
    path('RejactApplicants/<int:id>',views.RejactApplicants,name='RejactApplicants'),
    path('sineup/',views.sineup,name='sineup'),
    path('register/',views.register,name='register'),
    path('ApplicantInfo/<int:id>',views.ApplicantInfo,name='ApplicantInfo'),

    # path('jet_api/', include('jet_django.urls')),
    # url(r'^jet/', include('jet.urls', 'jet')), #django jet urls
    # url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS


]

visit/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User

from .validators import validate_file_extension, content_file_name,Applicant_photo
from datetime import *
from django.db.models import DO_NOTHING

# Create your models here.

# class User(AbstractUser):
#     is_security = models.CharField(max_length=20) 




class Student(models.Model):

    name = models.CharField(max_length=150, null=True)
    contact = models.PositiveIntegerField(null=True)
    email = models.EmailField(max_length=150, null=True)
    address = models.CharField(max_length=250, null=True)
    college = models.CharField(max_length=250, null=True)
    photo = models.ImageField(upload_to = content_file_name, validators = [validate_file_extension], null=True)
    date = models.DateField(null=True, default=date.today)
    from_time = models.TimeField(null=False, default=datetime.now())
    to_time = models.TimeField(null=False)
    purpose = models.CharField(max_length=150, null=True)
    status = models.CharField(max_length=20,default="pending")
    # student_entry_time=models.CharField(null=True,default="",max_length=20,blank=True)
    # student_exit_time=models.CharField(null=True,default="",max_length=20,blank=True)
    student_entry_time = models.TimeField(null=True,default=None,blank=True)
    student_exit_time = models.TimeField(null=True,default=None,blank=True)


    def __str__(self):
        return self.name


class Applicant(models.Model):
    username=models.CharField(max_length=150,unique = True)
    email=models.EmailField(max_length=150,unique = True)
    firstname=models.CharField(max_length=150)
    lastname=models.CharField(max_length=150)
    id_name=models.CharField(max_length=150)
    id_num=models.CharField(max_length=150)
    contact=models.CharField(max_length=150,unique = True)
    address=models.CharField(max_length=150)
    role=models.CharField(max_length=20,choices=(("HR","HR"),("Security","Security")))
    
    # photo = models.ImageField(upload_to=Applicant_photo)
    status = models.CharField(max_length=20,default="pending")
    def __str__(self):
        return self.username

class Security(models.Model):
    security_user = models.ForeignKey(User,on_delete=DO_NOTHING)
    student_id = models.ForeignKey(Student,on_delete=DO_NOTHING)
    class Meta:
     permissions = (
           ("is_Security", "Can edit the entry time of a student or employee"),
     )
class HR(models.Model):
    hr_user=models.ForeignKey(User,on_delete=DO_NOTHING)
    class Meta:
         permissions = (
           ("is_hr", "Can edit the meeting time of a visitor"),
     )

visit/views.py
import json

from django.http.response import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views.generic.edit import DeleteView

from .forms import StudentVisitForm, HrUpdateTimeForm,  SineUpForm,SineUpForm1,SecurityTimeForm, PasswordChangingForm
from .models import Student,Applicant
from .decorators import unauthenticated_user
from datetime import datetime
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Group
# Create your views here.
    
# from .filters import StudentFilter




import math
import http

def sineup(request):
    form = SineUpForm()
    if request.method=="POST":
        role=request.POST['role']
        status = "pending"
        form = SineUpForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # return HttpResponse("Thanks")
            form = SineUpForm()
            return render(request,"visit/sineup.html",{'error1':"User Succussfully Registered",'form': form})
        else:
            return render(request,"visit/sineup.html",{'error':"User Alredy Exist With This Details",'form': form})
    return render(request,"visit/sineup.html",{'form': form})

def register(request):
    form = SineUpForm1()
    if request.method=="POST":
        role=request.POST['role']
        status = "Accepted"
        form = SineUpForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            id=Applicant.objects.all().count()
            ap = Applicant.objects.get(pk=id)
            name_r = ap.username
            email_r = ap.email

            password_r = name_r.title()+'@123'
            recipent_email=(ap.email,)
            email_from=settings.EMAIL_HOST_USER
            try:
                user=User.objects.create_user(name_r, email_r, password_r,is_staff=True)
                Applicant.objects.filter(pk=id).update(status="Accepted")
                my_group  = Group.objects.get(name=ap.role) 
                # my_group.user_set.add(ap)
                user.groups.add(my_group)
                print(my_group)
                subject="Application Accepted"
                messages=(f"Your Applicatition Has Been Approved.Your Username is --> {name_r} and Password is --> {password_r}")
                send_mail(subject, messages,email_from, recipent_email)
                context={}
                form = SineUpForm1()

                context['form']=form
                context['error1']="User Created Succesfully"
                return render(request,'visit/register.html',context)
            except:
                return render(request,"visit/register.html",{'error':"User Alredy Exist With This Details",'form': form})
        else:
            return render(request,"visit/register.html",{'error':"User Alredy Exist With This Details",'form': form})
    return render(request,"visit/register.html",{'form': form})

def newvisitor(request):
    form = StudentVisitForm()
    if request.method == 'POST':
        form = StudentVisitForm(request.POST, request.FILES)
        if form.is_valid():
            
            status = request.POST['status']
            from_time=request.POST['from_time']
            to_time=request.POST['to_time']
            date=request.POST['date']
            time=datetime.now().time()
            date1=datetime.now().date()
            date_time_str = date+" "+from_time
            date_time_obj = datetime.strptime(date_time_str, '%Y-%m-%d %H:%M')
            from_time1=date_time_obj.time()
            date2=date_time_obj.date()
            if date2>date1:
                if  from_time>to_time:
                    return render(request,'visit/newvisitor.html', {'form': form,'error':'please enter a valid time duration'})
                else:
                    form.save()
            elif from_time1<time and from_time>to_time:
                return render(request,'visit/newvisitor.html', {'form': form,'error':'please enter a valid time duration'})
            else:
                form.save()
            id= Student.objects.all().count()
            st= Student.objects.get(pk=id)
            Student.objects.filter(pk=id).update(status="Accepted")
            print(st.email)
            recipent_email=(st.email,)
            subject="Meeting confirmed"
            messages=(f"you can check your remaning time to meeting is here--> http://127.0.0.1:8000/RemaningTimeToMeet/{st.id} and your id is {st.id}")
            email_from=settings.EMAIL_HOST_USER
            send_mail(subject, messages,email_from, recipent_email)
            form = StudentVisitForm()
            return render(request, 'visit/newvisitor.html', {'form': form,"messages":"Meeting Registered Succussfully"})
            # messages.success(request, 'A visit is requested by'+name)
    return render(request, 'visit/newvisitor.html', {'form': form})



def home(request):
    form = StudentVisitForm()
    if request.method == 'POST':
        form = StudentVisitForm(request.POST, request.FILES)
        if form.is_valid():
            
            status = request.POST['status']
            from_time=request.POST['from_time']
            to_time=request.POST['to_time']
            date=request.POST['date']
            time=datetime.now().time()
            date1=datetime.now().date()
            date_time_str = date+" "+from_time
            date_time_obj = datetime.strptime(date_time_str, '%Y-%m-%d %H:%M')
            from_time1=date_time_obj.time()
            date2=date_time_obj.date()
            if date2>date1:
                if  from_time>to_time:
                    return render(request,'visit/home.html', {'form': form,'error':'please enter a valid time duration'})
                else:
                    form.save()
                    return HttpResponse("Thanks")
            elif from_time1<time:
                return render(request,'visit/home.html', {'form': form,'error':'please enter a valid time duration time is not before now'})
            else:
                form.save()
                form = StudentVisitForm()
                return render(request, 'visit/home.html', {'form': form,"messages":"Request sent Succussfully"})
            # messages.success(request, 'A visit is requested by'+name)
    return render(request, 'visit/home.html', {'form': form})


@unauthenticated_user 
def loginpage(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('visit:dashboard'))
        else:
            messages.info(request, 'Username or Password is incorrect!!')
    return render(request, 'visit/login.html')

@login_required(login_url='/login/')
def logoutUser(request):
    logout(request)
    return redirect(reverse('visit:login'))
    # return redirect('/login/')


@login_required(login_url='/login/')
def dashboard(request):
    total_visit = Student.objects.all().count()
    completed_visit = Student.objects.filter(status="Completed").count()
    panding_visit = Student.objects.filter(status="Accepted").count()
    completed_visit_today = Student.objects.filter(status="Completed",date=datetime.now().date()).count()
    panding_visit_today = Student.objects.filter(status="Accepted",date=datetime.now().date()).count()
    today_total_visit=Student.objects.filter(date=datetime.now().date()).count()
    
    
    context = {'total_visit': total_visit,'panding_visit':panding_visit,"completed_visit_today":completed_visit_today,"completed_visit":completed_visit,"today_total_visit":today_total_visit,"panding_visit_today":panding_visit_today}
    if request.user.is_superuser:
        return render(request, 'visit/dashboard.html', context)
    elif request.user.has_perm("visit.is_hr"):
        return render(request, 'visit/dashboard.html', context)
    elif request.user.has_perm("visit.is_Security"):
        visitor = Student.objects.all().order_by('id').reverse()
        data = visitor.values()
        page_number = request.GET.get('page')
        context = pagination(visitor, page_number)
        return render(request, 'visit/Security.html', context)
    else:
        return render(request, 'visit/dashboard.html', context)

def pagination(visitor, page_number):
    paginator = Paginator(visitor, 7, orphans=1)
#    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    print("Page Object:", page_obj)

    context = {'page_obj': page_obj}

    return context

# @login_required(login_url='/login/')
# @permission_required('visit.is_hr')
# def visitors(request):
#     visitor = Student.objects.all().order_by('id')
#     data = visitor.values()
#     page_number = request.GET.get('page')
#     context = pagination(visitor, page_number)
#     return render(request, 'visit/visitor1.html', context)
@login_required(login_url='/login/')
@permission_required('visit.is_hr')
def visitors(request):
    visitor = Student.objects.all().order_by('date').reverse()
    pending_visit = Student.objects.filter(date=datetime.now().date()).filter(status='pending')[0:6:-1]
    print("pending visit : ", pending_visit)
    data = visitor.values()
    page_number = request.GET.get('page')
    context = pagination(visitor, page_number)
    context['pending_visit'] = pending_visit
    return render(request, 'visit/visitor1.html', context)

@login_required(login_url='/login/')

visit/templates/visit/123.html
https://stackoverflow.com/questions/14830669/how-to-expire-django-session-in-5minutes
https://docs.djangoproject.com/en/3.2/topics/http/sessions/
https://pypi.org/project/django-session-timeout/

visit/templates/visit/home.html
{% extends 'base1.html' %}
{% load static %}
{% block core_css%}
<style>
  body {
    background: #eee;
  }
  .emp-profile {
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
    box-shadow:0 10px 16px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19) !important;
  }
  .profile-img {
    text-align: center;
  }
  .profile-img img {
    width: 70%;
    height: 100%;
  }
  .profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
  }
  .profile-head h1 {
    color: #333;
  }
  .profile-head h5 {
    color: #0062cc;
  }
  .profile-edit-btn {
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
  }
  .proile-rating {
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
  }
  .proile-rating span {
    color: #495057;
    font-size: 15px;
    font-weight: 600;
  }
  .profile-head .nav-tabs {
    margin-bottom: 5%;
  }
  .profile-head .nav-tabs .nav-link {
    font-weight: 600;
    border: none;
  }
  .profile-head .nav-tabs .nav-link.active {
    border: none;
    border-bottom: 2px solid #0062cc;
  }
  .profile-work {
    padding: 14%;
    margin-top: -15%;
  }
  .profile-work p {
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
  }
  .profile-work a {
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
  }
  .profile-work ul {
    list-style: none;
  }
  .profile-tab label {
    font-size: 20px;
    font-weight: bold;
    text-transform: capitalize;
    text-align: center;
  }
  .profile-tab p {
    font-weight: 600;
    color: #0062cc;
    text-transform: capitalize;
  }
</style>
<style>
.alert {
  padding: 20px;
  background-color: #f44336;
  color: white;
  opacity: 1;
  transition: opacity 0.6s;
  margin-bottom: 15px;
}

.alert.success {background-color: #04AA6D;}

.closebtn {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtn:hover {
  color: black;
}
</style>
{%endblock core_css%}
{% block style %}


<style>
  #showPasswordToggle {
    cursor: pointer;
    transition: all;
    margin-left: 85%;
  }

</style>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
{% endblock style%}


{% block content %}
<body style="background: #eee;">

{% comment %} <a href="\login\">Login</a> {% endcomment %}
<div class="container emp-profile">
<div class="row">
{% comment %} <h1 class="ml-4">Register Your Visit</h1> {% endcomment %}

  <div class="col-md-12">
    <div>
    {% if messages %}
    <div class="alert success">
  <span class="closebtn">&times;</span>  
  <strong>Success!</strong>{{messages}} .
</div>
{% endif %}
  <script>
var close = document.getElementsByClassName("closebtn");
var i;

for (i = 0; i < close.length; i++) {
  close[i].onclick = function(){
    var div = this.parentElement;
    div.style.opacity = "0";
    setTimeout(function(){ div.style.display = "none"; }, 600);
  }
}
</script>

      <div class="contact-form">
        {% comment %} <a class="close">&times;</a> {% endcomment %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Visit Request</h2>
            <div class="row">
                <div class="col-sm">
                  <div class="form-group mb-2">
                      <label for="id_name">Name</label>  
                      {{form.name}}
                    </div>                  
                </div>              
            </div>
            <div class="row">
                <div class="col-sm">
                  <div class="form-group mb-2">
                      <label for="id_contact">Contact</label>
                      {{form.contact}}
                  </div>
                </div>
                <div class="col-sm">
                  <div class="form-group mb-2">
                      <label for="id_email">Email</label>
                      {{form.email}}
                  </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group mb-2">
                        <label for="id_Address">Address</label>
                        {{form.address}}
                    </div>
                  </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group mb-2">
                        <label for="id_email">College</label>
                        {{form.college}}
                    </div>
                  </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group mb-2">
                        <label for="id_photo">Photo</label>
                        {{form.photo}}
                    </div>
                </div>
                
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group mb-2">
                        <label for="id_date">Date Visiting</label>
                        {{form.date}}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group mb-2">
                        <label for="from_time">Visiting Time</label>
                        {{form.from_time}}
                    </div>
                </div>
            
                <div class="col-sm">
                    <div class="form-group mb-2">
                        <label for="to_time">&nbsp</label>
                        {{form.to_time}}
                    </div>
                </div>
            </div>
            <span style="color:red">{{error}}</span>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group mb-2">
                        <label for="id_purpose">Purpose</label>
                        {{form.purpose}}
                    </div>
                </div>
            </div>
            <input type='text' hidden value='pending' id='status' name='status'>
            <button type="submit">Submit</button>
        </form>
    </div>
    </div>
    <div id="modalTwo" class="tab-pane">

  </div>
</div>

{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.4/moment.js"></script>
    <script>
    var today = new Date();
    if(dd<10){
    dd='0'+dd
    } 
    if(mm<10){
    mm='0'+mm
    }
    var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
    today =  today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();
    
   document.getElementById("datefield").setAttribute("min",today1);
    var from = $("input[name='from_time[]']").val(); 
    var to = $("input[name='to_time[]']").val(); 
    if (moment(from, 'hh:mm a') > moment(to, 'hh:mm a')) {
  alert("Invalid Date Range");
} else {
  alert("Valid Date Range");
}
    </script>   
    
{% endblock javascript %}
<script>
$(document).ready(function () {
    $('.nav li a').click(function(e) {

        $('.nav li.active').removeClass('active');

        var $parent = $(this).parent();
        $parent.addClass('active');
        e.preventDefault();
    });
});

</script> 
    <script>
    $(document).ready(function(){
    $('.nav li').click(function(event){
        //remove all pre-existing active classes
        $('.active').removeClass('active');

        //add the active class to the link we clicked
        $(this).addClass('active');

        //Load the content
        //e.g.
        //load the page that the link was pointing to
        //$('#content').load($(this).find(a).attr('href'));
        event.preventDefault();
    });
});
    </script>
<!-- {{form.as_p}} -->

{% endblock %}

visit/templates/visit/navbar.html
{% load static %}
<style></style>

<nav class="navigation navbar navbar-expand-lg navbar-transparent">
  <a class="navbar-brand" href="{% url 'visit:dashboard' %}">VMS LOGO</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarTogglerDemo03"
    aria-controls="navbarTogglerDemo03"
    aria-expanded="true"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse ml" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      {% if request.user.is_staff and perms.visit.is_hr %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'visit:dashboard' %}"
          >Home <span class="sr-only">(current)</span></a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'visit:visitor' %}">Visitors</a>
      </li>
      {% elif request.user.is_staff and perms.visit.is_Security %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'visit:security_page' %}">Security Page</a>
      </li>

      {% else %}
      <li class="nav-item">
        <a class="nav-link disabled" href="">Create visit</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="">Settings</a>
      </li>
      {% endif %}
    </ul>
    <!-- <span class="notifications mr-3">
      <a href="#"><i class="mdi mdi-bell auti-custom-input-icon"></i></a>
      
    </span> -->

    <ul class="navbar-nav mx-auto float-right">
      <li class="nav-item">
        <span class="hello-msg text-white">Hello, {{request.user}} </span>
      </li>
      <li class="nav-item">
        <span><a class="nav-link" href="">Change Password</a></span>
      </li>
      <li class="nav-item">
        <span
          ><a class="nav-link" href="{% url 'visit:logout' %}">Logout</a></span
        >
      </li>
    </ul>
  </div>
</nav>

visit/templates/visit/navbar1.html
{% load static %}
<!-- Topbar Start -->

   <!-- LOGO -->     
<div id="wrapper">
   <div class="navbar-custom">

   <div class="logo-box">
       
   </div>
         <ul class="list-unstyled topnav-menu topnav-menu-left mb-0">
          <li>
              <button class="button-menu-mobile disable-btn waves-effect">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
</svg>
              </button>
          </li>   
      </ul>
      <!-- Topbar Start -->

   <ul class="list-unstyled topnav-menu float-right mb-0">
       <li class="dropdown notification-list">
           <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
            <img src="{% static 'images/user_icon.png' %}" alt="user-image" class="rounded-circle">
               <span class="pro-user-name ml-1">
                   {{user.username}} <i class="mdi mdi-chevron-down"></i> 
               </span>
           </a>
           <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
               <!-- item-->
               <div class="dropdown-header noti-title">
                   <h6 class="text-overflow m-0">Welcome !</h6>
               </div>

               <!-- item-->
               <a href="{% url 'visit:changepass' %}" class="dropdown-item notify-item" style="display:flex;">
                   <i class="mdi mdi-plus"></i>
                   <span>Change Password</span>
               </a>               

               <div class="dropdown-divider"></div>

               <!-- item-->
               <a href="{% url 'visit:logout' %}" class="dropdown-item notify-item" style="display:flex;">
                   <i class="mdi mdi-logout"></i>
                   <span>Logout</span>
               </a>

           </div>
       </li>


   </ul>
      {% comment %} <ul>
      <li>
          <a href="#">
          <i  style="color: white;"  class="mdi mdi-account-convert"></i>
          Hello,{{user}}<span class="menu-arrow"></span>
                    </a>
                    <ul class="nav-second-level" aria-expanded="false">
                        <li><a href="{% url 'visit:changepass' %}"><i  style="color: white;" class="mdi mdi-plus"></i>Change Password</a></li>
                        <li><a href="{% url 'visit:logout' %}"><i  style="color: white;" class="mdi mdi-logout"></i>Log out</a></li>
                    </ul>
                </li>
</ul> {% endcomment %}
  </div>
   {% include 'visit/sidebar.html' %}


<div class="content-page">
 <div class="content">

<!-- end Topbar -->